gesdinet_jwt_refresh_token:
  refresh_token_class: App\Entity\RefreshToken
  ttl: 2592000
  firewall: refresh
  user_provider: app_user_provider
  single_use: true
  cookie:
    enabled: true
    http_only: true
    secure: false # true en prod HTTPS
    same_site: lax
    path: /